74 bug nao e possivel adicionar e remover topicos
ceos-jr/odyssey-proativa pull request #84
Opened 2023-06-13 12:05 UTC by Pedro6508

# Description
Closes #74 

Problema: Não era possível criar e remover tópicos em módulo pre-existente, essas são as fetuares implementadas para que isso seja possível agora: 

- Novo arquivo "src/pages/modules/[moduleId]/edit.tsx": 
	- É a pagina do frontend em que o usuário usa para editar o módulo.
- Novo arquivo "src/utils/indexRules.ts": 
	- Padroniza a forma como um modulo que está sendo criado/editado ordena seus tópicos no front-end, evitando:
		- movimentação para posições inválidas, 
		- duplicidade de index,
		- comportamentos inesperados com o index '0 ' (number),
		- e outras pequenas diferenças de comportamento entre as paginas "edit.tsx" e "create.tsx" em "src/pages/modules/...".
	- A ideia é que no futuro o indexRules gerencie toda a lógica de index do projeto ou no mínimo dos módulos, por isso atualmente ele possui alguns metodos e atributos subutilizados.
- Nova rota "editModule: adminProcedure" em "modules.ts": 
	- Essa rota gerência a edição de um modulo, ou seja:
		- atualiza as lessons que já existem e continuam existindo,
		- deleta as lessons que existiam e foram deletadas,
		- cria as lessons que não existiam previamente e seus respectivos progressos,
		- e atualiza a ordem de todas as restantes atualizadas + criadas).
	- Atualmente isso é feito usando o index da lesson no array de input, mas esse index, por certos motivos, não necessariamente se equivale ao index gerenciado pelo indexRules. 
	- Em geral essa rota interfere em varias partes do projeto ao mesmo tempo( lessons, modules, lessonProgress, moduleProgres, ...) e não acredito que seja produtivo refatora-la sem a implementação de testes, dado que essa versão parece estável.

## Tipo de mudança

- [x] Bug fix (mudança não críticaque conserta uma issue)
- [x] New feature (mudança não crítica que adiciona uma nova feature)
- [x] Mudança crítica (Concerto ou uma feature que pode quebrar funcionalidades antigas)
- [ ] Apenas mudança de documentação

# Como ele tem sido testado?

As fetures foram todas testadas manualmente, mas seguindo um padrão:
 - Testes de ordem:
	 - [x] MoveUp* e MoveDown* são sempre válidos e corretos.
	 - [x] PróximaLess e AnteriorLess são sempre válidos e corretos.
	 - [x] A nova ordem das  lessons após uma edição é correta e o valor *null* está presente como antecessor do primeiro e posterior do último.
	 - [x] As lógicas de ordem entre as paginas "edit.tsx" e "create.tsx" são iguais ou intercoverssíveis.
	 - [x] A rota "editModule" gera resultados equivalentes entre lessons que foram criadas e lessons que foram criadas e atualizadas. 
 - Testes de Consistência: 
	 - [x] Uma lesson que foi apagada em uma edição é também é deletada no banco de dados.
	 - [x] Uma lesson que foi criada na edição é também é criada no banco de dados.
	 - [x] Uma lesson que não foi criada e nem deletada é atualizada.
	 - [x] A ordem de todas as lessons restantes no módulo são atualizadas.
	 - [x] Todos os Progressos* atualizados ou deletados corretamente.

*MoveUp/MoveDown: movimentos das lessons no front-end
*PróximaLess/AnteriorLess: ir de uma lesson para a próxima ou anterior
*Progressos: dados referentes aos progressos dos usuários em relação as lessons, modulos e tasks.

# Checklist:

- [x] Realizei uma revisão do meu código
- [x] Eu comentei meus códigos, particularmente nas aŕeas mais difíceis
- [ ] Eu fiz as mudanças correspondentes na documentação
- [ ] Minhas mudanças não geraram nenhum warning
- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que minha feature funciona
- [ ] Testes unitários novos e já pre-existentes foram aprovados localmente
- [x] Qualquer mudança pendente na main branch já foi implementada nessa branch

2023-06-14 16:52 UTC, talDoFlemis requested changes
algumas mudancas opcionais e outras nao

2023-06-15 00:19 UTC, Lu1z-Gust4v0 commented on src/pages/modules/[moduleId]/edit.tsx
> +                    <Button
Ponto discutido em reunião. Optamos pela permanencia desta lógica de delete. Vamos estudar a modificação da mensagem no popup.

2023-06-17 02:35 UTC, Lu1z-Gust4v0 commented on src/pages/modules/[moduleId]/edit.tsx
> +                  <FormLabel>Nome do tópico{field.index}</FormLabel>
Removido

2023-06-17 02:36 UTC, Lu1z-Gust4v0 commented on src/pages/modules/[moduleId].tsx
> +                      <Button
Resolvido

2023-06-17 16:26 UTC, talDoFlemis requested changes
só esse detalhe, ai vcs podem torar o quanto quiserem

2023-06-17 16:26 UTC, talDoFlemis commented on src/pages/modules/[moduleId].tsx
> +                      <Button leftIcon={<AiOutlineDelete />} colorScheme="blue">
Icone do Editar tá o de deletar

2023-06-17 22:00 UTC, Pedro6508 commented on src/pages/modules/[moduleId].tsx
> +                      <Button leftIcon={<AiOutlineDelete />} colorScheme="blue">
Resolvi isso, dei uma ajustada na responsividade depois para fica tudo ok.

2023-06-18 20:43 UTC, talDoFlemis approved these changes
aprovado

2023-06-18 20:44 UTC, merged