Indicação onde o usuário está
ceos-jr/odyssey-proativa pull request #94
Opened 2023-08-02 00:24 UTC by Jonaires777

# Description

Closes # (linke sua issue aqui)

## Tipo de mudança

- [ ] Bug fix (mudança não críticaque conserta uma issue)
- [ ] New feature (mudança não crítica que adiciona uma nova feature)
- [ ] Mudança crítica (Concerto ou uma feature que pode quebrar funcionalidades antigas)
- [ ] Apenas mudança de documentação

# Checklist:

- [ ] Realizei uma revisão do meu código
- [ ] Eu comentei meus códigos, particularmente nas aŕeas mais difíceis
- [ ] Eu fiz as mudanças correspondentes na documentação
- [ ] Minhas mudanças não geraram nenhum warning
- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que minha feature funciona
- [ ] Testes unitários novos e já pre-existentes foram aprovados localmente
- [ ] Qualquer mudança pendente na main branch já foi implementada nessa branch

2023-08-02 16:55 UTC, talDoFlemis requested changes
.

2023-08-02 16:55 UTC, talDoFlemis commented on package.json
> +    "@chakra-ui/icons": "^2.1.0",
Pq vc adicionou o chakra icons? O `React-icons` não é suficiente para você?

2023-08-02 16:55 UTC, talDoFlemis commented on package.json
> +    "titlecase": "^1.1.3",
Você consegue perfeitamente fazer isso com javascript nativo, 3 linhas você resolve isso. Não há nenhuma necessidade para se fazer o uso de uma nova library

2023-08-02 16:55 UTC, talDoFlemis commented on src/components/Layout/DynamicBreadcrumb.tsx
> +    useEffect(() => {
concertar aqueles bugs que a gente viu ontem

2023-08-08 20:33 UTC, Jonaires777 commented on package.json
> +    "@chakra-ui/icons": "^2.1.0",
Tirei, tava testando uns ícone no separador do breadcrumbs.

2023-08-14 21:27 UTC, talDoFlemis approved these changes
aprovado

2023-08-14 21:29 UTC, merged